CREATE TABLE IF NOT EXISTS  `ScoutMatchData`(
    `id` INT AUTO_INCREMENT NOT NULL,
    `event` VARCHAR(50) NOT NULL,
    `scout` INT NOT NULL,
    `team` INT NOT NULL,
    `match_number` INT NOT NULL,
    `field_position` INT NOT NULL,
    `attended` TINYINT NOT NULL,
    `auto_mobility` TINYINT,
    `auto_amp` TINYINT,
    `auto_speaker` TINYINT,
    `tele_amp` INT,
    `tele_speaker` INT,
    `onstage` TINYINT,
    `spotlight` TINYINT,
    `stage_light` TINYINT,
    `harmony` TINYINT,
    `coopertition` TINYINT,
    `win` TINYINT,
    `alliance_score` INT,
    `notes` VARCHAR(500),
    `melody` TINYINT,
    `ensemble` TINYINT,
    `created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    `modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (`scout`) REFERENCES `users`(`id`),
    FOREIGN KEY (`team`) REFERENCES `teams`(`id`),
    PRIMARY KEY (`id`)
)